// GENERATED FILE - do not edit by hand.
//
// Source of truth: supabase/migrations/*.sql, generated by
//   npx supabase gen types typescript --linked
// (or --db-url <DATABASE_URL>). Regenerate with:
//   ./scripts/generate-db-types.sh --linked
//
// private.quiz_answer_keys is intentionally absent: it lives in a schema the
// frontend role cannot read, so correct answers cannot reach the browser.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      attempt_answers: {
        Row: {
          attempt_id: string
          is_correct: boolean
          option_id: string
          question_id: string
        }
        Insert: {
          attempt_id: string
          is_correct: boolean
          option_id: string
          question_id: string
        }
        Update: {
          attempt_id?: string
          is_correct?: boolean
          option_id?: string
          question_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "attempt_answers_attempt_id_fkey"
            columns: ["attempt_id"]
            isOneToOne: false
            referencedRelation: "quiz_attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempt_answers_option_id_fkey"
            columns: ["option_id"]
            isOneToOne: false
            referencedRelation: "question_options"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempt_answers_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "quiz_questions"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: number
          metadata: Json
          reason: string | null
          target_id: string
          target_type: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: never
          metadata?: Json
          reason?: string | null
          target_id: string
          target_type: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: never
          metadata?: Json
          reason?: string | null
          target_id?: string
          target_type?: string
        }
        Relationships: []
      }
      certificates: {
        Row: {
          completed_at: string
          course_id: string
          course_title: string
          created_at: string
          enrollment_id: string
          failure_reason: string | null
          final_attempt_id: string
          final_score: number
          generation_lease_until: string | null
          generation_token: string | null
          id: string
          issued_at: string | null
          object_path: string | null
          pdf_sha256: string | null
          required_module_count: number
          revocation_reason: string | null
          revoked_at: string | null
          revoked_by: string | null
          size_bytes: number | null
          status: Database["public"]["Enums"]["certificate_status"]
          student_name: string
          template_sha256: string
          template_version: number
          updated_at: string
          user_id: string
          verification_id: string
        }
        Insert: {
          completed_at: string
          course_id: string
          course_title: string
          created_at?: string
          enrollment_id: string
          failure_reason?: string | null
          final_attempt_id: string
          final_score: number
          generation_lease_until?: string | null
          generation_token?: string | null
          id?: string
          issued_at?: string | null
          object_path?: string | null
          pdf_sha256?: string | null
          required_module_count: number
          revocation_reason?: string | null
          revoked_at?: string | null
          revoked_by?: string | null
          size_bytes?: number | null
          status?: Database["public"]["Enums"]["certificate_status"]
          student_name: string
          template_sha256: string
          template_version: number
          updated_at?: string
          user_id: string
          verification_id?: string
        }
        Update: {
          completed_at?: string
          course_id?: string
          course_title?: string
          created_at?: string
          enrollment_id?: string
          failure_reason?: string | null
          final_attempt_id?: string
          final_score?: number
          generation_lease_until?: string | null
          generation_token?: string | null
          id?: string
          issued_at?: string | null
          object_path?: string | null
          pdf_sha256?: string | null
          required_module_count?: number
          revocation_reason?: string | null
          revoked_at?: string | null
          revoked_by?: string | null
          size_bytes?: number | null
          status?: Database["public"]["Enums"]["certificate_status"]
          student_name?: string
          template_sha256?: string
          template_version?: number
          updated_at?: string
          user_id?: string
          verification_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "certificates_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "certificates_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: true
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "certificates_final_attempt_id_fkey"
            columns: ["final_attempt_id"]
            isOneToOne: false
            referencedRelation: "quiz_attempts"
            referencedColumns: ["id"]
          },
        ]
      }
      course_certificate_configs: {
        Row: {
          course_id: string
          enabled: boolean
          minimum_score: number
          required_module_count: number
          template_object_path: string
          template_sha256: string
          template_version: number
          updated_at: string
        }
        Insert: {
          course_id: string
          enabled?: boolean
          minimum_score: number
          required_module_count: number
          template_object_path: string
          template_sha256: string
          template_version: number
          updated_at?: string
        }
        Update: {
          course_id?: string
          enabled?: boolean
          minimum_score?: number
          required_module_count?: number
          template_object_path?: string
          template_sha256?: string
          template_version?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "course_certificate_configs_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: true
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      courses: {
        Row: {
          created_at: string
          currency: string
          description: string
          id: string
          price_centavos: number
          sales_enabled: boolean
          slug: string
          status: Database["public"]["Enums"]["course_status"]
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          currency?: string
          description?: string
          id?: string
          price_centavos: number
          sales_enabled?: boolean
          slug: string
          status?: Database["public"]["Enums"]["course_status"]
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          currency?: string
          description?: string
          id?: string
          price_centavos?: number
          sales_enabled?: boolean
          slug?: string
          status?: Database["public"]["Enums"]["course_status"]
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      email_delivery_events: {
        Row: {
          attempt: number
          created_at: string
          error: string | null
          event_type: string
          id: number
          outbox_id: string
          provider_message_id: string | null
        }
        Insert: {
          attempt: number
          created_at?: string
          error?: string | null
          event_type: string
          id?: never
          outbox_id: string
          provider_message_id?: string | null
        }
        Update: {
          attempt?: number
          created_at?: string
          error?: string | null
          event_type?: string
          id?: never
          outbox_id?: string
          provider_message_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "email_delivery_events_outbox_id_fkey"
            columns: ["outbox_id"]
            isOneToOne: false
            referencedRelation: "email_outbox"
            referencedColumns: ["id"]
          },
        ]
      }
      email_outbox: {
        Row: {
          attempts: number
          created_at: string
          failed_at: string | null
          id: string
          idempotency_key: string
          last_error: string | null
          lease_until: string | null
          lock_token: string | null
          locked_at: string | null
          next_attempt_at: string
          payload: Json
          provider_message_id: string | null
          recipient_user_id: string
          sent_at: string | null
          status: Database["public"]["Enums"]["email_status"]
          template: string
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          failed_at?: string | null
          id?: string
          idempotency_key: string
          last_error?: string | null
          lease_until?: string | null
          lock_token?: string | null
          locked_at?: string | null
          next_attempt_at?: string
          payload?: Json
          provider_message_id?: string | null
          recipient_user_id: string
          sent_at?: string | null
          status?: Database["public"]["Enums"]["email_status"]
          template: string
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          failed_at?: string | null
          id?: string
          idempotency_key?: string
          last_error?: string | null
          lease_until?: string | null
          lock_token?: string | null
          locked_at?: string | null
          next_attempt_at?: string
          payload?: Json
          provider_message_id?: string | null
          recipient_user_id?: string
          sent_at?: string | null
          status?: Database["public"]["Enums"]["email_status"]
          template?: string
          updated_at?: string
        }
        Relationships: []
      }
      enrollment_grants: {
        Row: {
          active: boolean
          created_at: string
          created_by: string
          enrollment_id: string
          id: string
          reason: string
          source_id: string | null
          source_type: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          created_by: string
          enrollment_id: string
          id?: string
          reason: string
          source_id?: string | null
          source_type: string
        }
        Update: {
          active?: boolean
          created_at?: string
          created_by?: string
          enrollment_id?: string
          id?: string
          reason?: string
          source_id?: string | null
          source_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "enrollment_grants_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
        ]
      }
      enrollment_modules: {
        Row: {
          created_at: string
          curriculum_version: number
          enrollment_id: string
          module_id: string
          required: boolean
        }
        Insert: {
          created_at?: string
          curriculum_version: number
          enrollment_id: string
          module_id: string
          required: boolean
        }
        Update: {
          created_at?: string
          curriculum_version?: number
          enrollment_id?: string
          module_id?: string
          required?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "enrollment_modules_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "enrollment_modules_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      enrollments: {
        Row: {
          course_id: string
          granted_at: string
          id: string
          status: Database["public"]["Enums"]["enrollment_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          course_id: string
          granted_at?: string
          id?: string
          status?: Database["public"]["Enums"]["enrollment_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          course_id?: string
          granted_at?: string
          id?: string
          status?: Database["public"]["Enums"]["enrollment_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "enrollments_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      material_access_events: {
        Row: {
          created_at: string
          enrollment_id: string | null
          event_type: string
          id: number
          module_id: string | null
          object_path: string
          user_id: string
        }
        Insert: {
          created_at?: string
          enrollment_id?: string | null
          event_type: string
          id?: never
          module_id?: string | null
          object_path: string
          user_id: string
        }
        Update: {
          created_at?: string
          enrollment_id?: string | null
          event_type?: string
          id?: never
          module_id?: string | null
          object_path?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "material_access_events_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "material_access_events_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      module_progress: {
        Row: {
          completed_at: string | null
          enrollment_id: string
          knowledge_check_completed_at: string | null
          module_id: string
          studied_at: string | null
          updated_at: string
        }
        Insert: {
          completed_at?: string | null
          enrollment_id: string
          knowledge_check_completed_at?: string | null
          module_id: string
          studied_at?: string | null
          updated_at?: string
        }
        Update: {
          completed_at?: string | null
          enrollment_id?: string
          knowledge_check_completed_at?: string | null
          module_id?: string
          studied_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "module_progress_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "module_progress_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      module_translations: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string
          id: string
          language: Database["public"]["Enums"]["app_language"]
          module_id: string
          object_path: string
          published: boolean
          purge_pending_at: string | null
          purge_reason: string | null
          purge_requested_by: string | null
          sha256: string
          size_bytes: number
          summary: string
          title: string
          version: number
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by: string
          id?: string
          language: Database["public"]["Enums"]["app_language"]
          module_id: string
          object_path: string
          published?: boolean
          purge_pending_at?: string | null
          purge_reason?: string | null
          purge_requested_by?: string | null
          sha256: string
          size_bytes: number
          summary?: string
          title: string
          version: number
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string
          id?: string
          language?: Database["public"]["Enums"]["app_language"]
          module_id?: string
          object_path?: string
          published?: boolean
          purge_pending_at?: string | null
          purge_reason?: string | null
          purge_requested_by?: string | null
          sha256?: string
          size_bytes?: number
          summary?: string
          title?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "module_translations_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      modules: {
        Row: {
          archived_at: string | null
          archived_from_status:
            | Database["public"]["Enums"]["module_status"]
            | null
          canonical_title: string | null
          course_id: string
          created_at: string
          curriculum_version: number
          id: string
          position: number
          required: boolean
          status: Database["public"]["Enums"]["module_status"]
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          archived_from_status?:
            | Database["public"]["Enums"]["module_status"]
            | null
          canonical_title?: string | null
          course_id: string
          created_at?: string
          curriculum_version?: number
          id?: string
          position: number
          required?: boolean
          status?: Database["public"]["Enums"]["module_status"]
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          archived_from_status?:
            | Database["public"]["Enums"]["module_status"]
            | null
          canonical_title?: string | null
          course_id?: string
          created_at?: string
          curriculum_version?: number
          id?: string
          position?: number
          required?: boolean
          status?: Database["public"]["Enums"]["module_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "modules_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          course_id: string
          created_at: string
          currency: string
          id: string
          price_centavos: number
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          course_id: string
          created_at?: string
          currency: string
          id?: string
          price_centavos: number
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          course_id?: string
          created_at?: string
          currency?: string
          id?: string
          price_centavos?: number
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_events: {
        Row: {
          actor_id: string
          created_at: string
          event_type: string
          id: number
          reason: string | null
          submission_id: string
        }
        Insert: {
          actor_id: string
          created_at?: string
          event_type: string
          id?: never
          reason?: string | null
          submission_id: string
        }
        Update: {
          actor_id?: string
          created_at?: string
          event_type?: string
          id?: never
          reason?: string | null
          submission_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "payment_events_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "payment_submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_methods: {
        Row: {
          destination_details: string | null
          destination_label: string | null
          display_name: string
          enabled: boolean
          id: string
          instructions: string | null
          qr_object_path: string | null
          type: Database["public"]["Enums"]["payment_method_type"]
          updated_at: string
        }
        Insert: {
          destination_details?: string | null
          destination_label?: string | null
          display_name: string
          enabled?: boolean
          id?: string
          instructions?: string | null
          qr_object_path?: string | null
          type: Database["public"]["Enums"]["payment_method_type"]
          updated_at?: string
        }
        Update: {
          destination_details?: string | null
          destination_label?: string | null
          display_name?: string
          enabled?: boolean
          id?: string
          instructions?: string | null
          qr_object_path?: string | null
          type?: Database["public"]["Enums"]["payment_method_type"]
          updated_at?: string
        }
        Relationships: []
      }
      payment_proof_revisions: {
        Row: {
          author_id: string
          created_at: string
          id: string
          mime_type: string
          object_path: string
          original_filename: string
          revision: number
          sha256: string
          size_bytes: number
          submission_id: string
        }
        Insert: {
          author_id: string
          created_at?: string
          id?: string
          mime_type: string
          object_path: string
          original_filename: string
          revision: number
          sha256: string
          size_bytes: number
          submission_id: string
        }
        Update: {
          author_id?: string
          created_at?: string
          id?: string
          mime_type?: string
          object_path?: string
          original_filename?: string
          revision?: number
          sha256?: string
          size_bytes?: number
          submission_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "payment_proof_revisions_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "payment_submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_submissions: {
        Row: {
          created_at: string
          id: string
          order_id: string
          payment_method_id: string
          reference_number: string
          review_reason: string | null
          reviewed_at: string | null
          reviewer_id: string | null
          status: Database["public"]["Enums"]["payment_status"]
          submitted_amount_centavos: number
          transaction_at: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          order_id: string
          payment_method_id: string
          reference_number: string
          review_reason?: string | null
          reviewed_at?: string | null
          reviewer_id?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          submitted_amount_centavos: number
          transaction_at: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          order_id?: string
          payment_method_id?: string
          reference_number?: string
          review_reason?: string | null
          reviewed_at?: string | null
          reviewer_id?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          submitted_amount_centavos?: number
          transaction_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "payment_submissions_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payment_submissions_payment_method_id_fkey"
            columns: ["payment_method_id"]
            isOneToOne: false
            referencedRelation: "payment_methods"
            referencedColumns: ["id"]
          },
        ]
      }
      policy_acceptances: {
        Row: {
          accepted_at: string
          policy_version_id: string
          user_id: string
        }
        Insert: {
          accepted_at?: string
          policy_version_id: string
          user_id: string
        }
        Update: {
          accepted_at?: string
          policy_version_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "policy_acceptances_policy_version_id_fkey"
            columns: ["policy_version_id"]
            isOneToOne: false
            referencedRelation: "policy_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      policy_versions: {
        Row: {
          content_hash: string
          effective_at: string | null
          id: string
          policy_type: string
          published: boolean
          version: string
        }
        Insert: {
          content_hash: string
          effective_at?: string | null
          id?: string
          policy_type: string
          published?: boolean
          version: string
        }
        Update: {
          content_hash?: string
          effective_at?: string | null
          id?: string
          policy_type?: string
          published?: boolean
          version?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          account_status: Database["public"]["Enums"]["account_status"]
          created_at: string
          full_name: string
          id: string
          preferred_language: Database["public"]["Enums"]["app_language"]
          updated_at: string
        }
        Insert: {
          account_status?: Database["public"]["Enums"]["account_status"]
          created_at?: string
          full_name: string
          id: string
          preferred_language?: Database["public"]["Enums"]["app_language"]
          updated_at?: string
        }
        Update: {
          account_status?: Database["public"]["Enums"]["account_status"]
          created_at?: string
          full_name?: string
          id?: string
          preferred_language?: Database["public"]["Enums"]["app_language"]
          updated_at?: string
        }
        Relationships: []
      }
      question_options: {
        Row: {
          id: string
          label: string
          position: number
          question_id: string
        }
        Insert: {
          id?: string
          label: string
          position: number
          question_id: string
        }
        Update: {
          id?: string
          label?: string
          position?: number
          question_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "question_options_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "quiz_questions"
            referencedColumns: ["id"]
          },
        ]
      }
      quiz_attempts: {
        Row: {
          attempt_number: number
          correct_count: number | null
          enrollment_id: string
          id: string
          kind: Database["public"]["Enums"]["quiz_kind"]
          passed: boolean | null
          question_count: number | null
          quiz_id: string
          quiz_version_id: string
          score: number | null
          scored_at: string | null
          started_at: string
          state: Database["public"]["Enums"]["attempt_state"]
          user_id: string
        }
        Insert: {
          attempt_number: number
          correct_count?: number | null
          enrollment_id: string
          id?: string
          kind: Database["public"]["Enums"]["quiz_kind"]
          passed?: boolean | null
          question_count?: number | null
          quiz_id: string
          quiz_version_id: string
          score?: number | null
          scored_at?: string | null
          started_at?: string
          state?: Database["public"]["Enums"]["attempt_state"]
          user_id: string
        }
        Update: {
          attempt_number?: number
          correct_count?: number | null
          enrollment_id?: string
          id?: string
          kind?: Database["public"]["Enums"]["quiz_kind"]
          passed?: boolean | null
          question_count?: number | null
          quiz_id?: string
          quiz_version_id?: string
          score?: number | null
          scored_at?: string | null
          started_at?: string
          state?: Database["public"]["Enums"]["attempt_state"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "quiz_attempts_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_attempts_quiz_id_fkey"
            columns: ["quiz_id"]
            isOneToOne: false
            referencedRelation: "quizzes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_attempts_quiz_version_id_fkey"
            columns: ["quiz_version_id"]
            isOneToOne: false
            referencedRelation: "quiz_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      quiz_questions: {
        Row: {
          created_at: string
          explanation: string
          id: string
          position: number
          prompt: string
          quiz_version_id: string
          required: boolean
        }
        Insert: {
          created_at?: string
          explanation?: string
          id?: string
          position: number
          prompt: string
          quiz_version_id: string
          required?: boolean
        }
        Update: {
          created_at?: string
          explanation?: string
          id?: string
          position?: number
          prompt?: string
          quiz_version_id?: string
          required?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "quiz_questions_quiz_version_id_fkey"
            columns: ["quiz_version_id"]
            isOneToOne: false
            referencedRelation: "quiz_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      quiz_versions: {
        Row: {
          cooldown_hours: number | null
          created_at: string
          created_by: string
          enabled: boolean
          id: string
          language: Database["public"]["Enums"]["app_language"]
          max_attempts: number | null
          pass_threshold: number | null
          published_at: string | null
          quiz_id: string
          source_sha256: string | null
          status: Database["public"]["Enums"]["quiz_version_status"]
          version: number
        }
        Insert: {
          cooldown_hours?: number | null
          created_at?: string
          created_by: string
          enabled?: boolean
          id?: string
          language: Database["public"]["Enums"]["app_language"]
          max_attempts?: number | null
          pass_threshold?: number | null
          published_at?: string | null
          quiz_id: string
          source_sha256?: string | null
          status?: Database["public"]["Enums"]["quiz_version_status"]
          version: number
        }
        Update: {
          cooldown_hours?: number | null
          created_at?: string
          created_by?: string
          enabled?: boolean
          id?: string
          language?: Database["public"]["Enums"]["app_language"]
          max_attempts?: number | null
          pass_threshold?: number | null
          published_at?: string | null
          quiz_id?: string
          source_sha256?: string | null
          status?: Database["public"]["Enums"]["quiz_version_status"]
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "quiz_versions_quiz_id_fkey"
            columns: ["quiz_id"]
            isOneToOne: false
            referencedRelation: "quizzes"
            referencedColumns: ["id"]
          },
        ]
      }
      quizzes: {
        Row: {
          course_id: string
          created_at: string
          id: string
          kind: Database["public"]["Enums"]["quiz_kind"]
          module_id: string | null
        }
        Insert: {
          course_id: string
          created_at?: string
          id?: string
          kind: Database["public"]["Enums"]["quiz_kind"]
          module_id?: string | null
        }
        Update: {
          course_id?: string
          created_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["quiz_kind"]
          module_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quizzes_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quizzes_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      refund_requests: {
        Row: {
          id: string
          reason: string
          request_channel: string
          requested_at: string
          review_reason: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["refund_request_status"]
          submission_id: string
        }
        Insert: {
          id?: string
          reason: string
          request_channel: string
          requested_at?: string
          review_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["refund_request_status"]
          submission_id: string
        }
        Update: {
          id?: string
          reason?: string
          request_channel?: string
          requested_at?: string
          review_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["refund_request_status"]
          submission_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "refund_requests_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: true
            referencedRelation: "payment_submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      refunds: {
        Row: {
          access_revoked: boolean
          amount_centavos: number
          certificate_decision: string
          created_at: string
          currency: string
          external_reference: string
          id: string
          recorded_by: string
          refunded_at: string
          request_id: string
          submission_id: string
        }
        Insert: {
          access_revoked?: boolean
          amount_centavos: number
          certificate_decision?: string
          created_at?: string
          currency: string
          external_reference: string
          id?: string
          recorded_by: string
          refunded_at: string
          request_id: string
          submission_id: string
        }
        Update: {
          access_revoked?: boolean
          amount_centavos?: number
          certificate_decision?: string
          created_at?: string
          currency?: string
          external_reference?: string
          id?: string
          recorded_by?: string
          refunded_at?: string
          request_id?: string
          submission_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "refunds_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: true
            referencedRelation: "refund_requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "refunds_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: true
            referencedRelation: "payment_submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      user_roles: {
        Row: {
          created_at: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          role: string
          user_id: string
        }
        Update: {
          created_at?: string
          role?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_payment_proof_revision: {
        Args: {
          amount_centavos: number
          paid_at: string
          payment_reference: string
          proof_filename: string
          proof_mime: string
          proof_path: string
          proof_sha256: string
          proof_size: number
          submission_user_id: string
          target_method_id: string
          target_submission: string
        }
        Returns: string
      }
      admin_add_module_to_enrollments: {
        Args: { reason: string; target_module: string }
        Returns: number
      }
      admin_archive_material_version: {
        Args: {
          reason: string
          replacement_translation?: string
          target_translation: string
          unpublish_material?: boolean
        }
        Returns: Json
      }
      admin_archive_module: {
        Args: { reason: string; target_module: string }
        Returns: Json
      }
      admin_edit_module: {
        Args: {
          apply_to_existing?: boolean
          new_canonical_title: string
          new_position: number
          new_required: boolean
          new_status: string
          reason: string
          target_module: string
        }
        Returns: Json
      }
      admin_edit_module_details: {
        Args: {
          cebaya_summary: string
          cebaya_title: string
          english_summary: string
          english_title: string
          new_canonical_title: string
          reason: string
          target_module: string
        }
        Returns: Json
      }
      admin_finalize_material_version_purge: {
        Args: { caller_user: string; target_translation: string }
        Returns: Json
      }
      admin_financial_ledger: {
        Args: { from_date: string; through_date: string }
        Returns: {
          event_at: string
          event_type: string
          gross_centavos: number
          net_centavos: number
          order_id: string
          reference_number: string
          refund_centavos: number
          student_id: string
          submission_id: string
        }[]
      }
      admin_knowledge_check_gaps: {
        Args: never
        Returns: {
          check_available: boolean
          check_exists: boolean
          gap: string
          module_id: string
          module_position: number
          module_status: Database["public"]["Enums"]["module_status"]
          title: string
        }[]
      }
      admin_material_version_impact: {
        Args: { target_translation: string }
        Returns: Json
      }
      admin_module_delete_impact: {
        Args: { target_module: string }
        Returns: Json
      }
      admin_purge_module: {
        Args: { reason: string; target_module: string }
        Returns: Json
      }
      admin_request_material_version_purge: {
        Args: {
          caller_user: string
          reason: string
          target_translation: string
        }
        Returns: Json
      }
      admin_restore_module: {
        Args: {
          reason: string
          restore_requirement?: boolean
          target_module: string
        }
        Returns: Json
      }
      admin_save_module: {
        Args: {
          action: string
          module_position: number
          module_required: boolean
          target_course: string
        }
        Returns: string
      }
      admin_save_module_translation: {
        Args: {
          asset_object_path: string
          asset_sha256: string
          asset_size_bytes: number
          caller_user: string
          publish_now?: boolean
          target_module: string
          translation_language: string
          translation_summary: string
          translation_title: string
        }
        Returns: Json
      }
      admin_set_course_sales: {
        Args: { sales: boolean; target_course: string }
        Returns: undefined
      }
      admin_set_module_status: {
        Args: {
          apply_to_existing?: boolean
          new_status: string
          reason: string
          target_module: string
        }
        Returns: undefined
      }
      admin_set_translation_published: {
        Args: {
          caller_user: string
          publish_now: boolean
          reason: string
          target_translation: string
        }
        Returns: undefined
      }
      certificate_eligibility: {
        Args: { target_enrollment: string }
        Returns: Json
      }
      check_certificate_rate_limit: {
        Args: { request_key_hash: string }
        Returns: boolean
      }
      claim_certificate_generation: {
        Args: { target_certificate: string; worker_token: string }
        Returns: Json
      }
      claim_email_outbox: {
        Args: { batch_size?: number; worker_name: string }
        Returns: {
          attempt: number
          id: string
          idempotency_key: string
          lock_token: string
          payload: Json
          recipient_user_id: string
          template: string
        }[]
      }
      complete_certificate_generation: {
        Args: {
          generated_object_path: string
          generated_sha256: string
          generated_size: number
          target_certificate: string
          worker_token: string
        }
        Returns: {
          completed_at: string
          course_id: string
          course_title: string
          created_at: string
          enrollment_id: string
          failure_reason: string | null
          final_attempt_id: string
          final_score: number
          generation_lease_until: string | null
          generation_token: string | null
          id: string
          issued_at: string | null
          object_path: string | null
          pdf_sha256: string | null
          required_module_count: number
          revocation_reason: string | null
          revoked_at: string | null
          revoked_by: string | null
          size_bytes: number | null
          status: Database["public"]["Enums"]["certificate_status"]
          student_name: string
          template_sha256: string
          template_version: number
          updated_at: string
          user_id: string
          verification_id: string
        }
        SetofOptions: {
          from: "*"
          to: "certificates"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      create_order: {
        Args: { course_slug: string }
        Returns: {
          course_id: string
          created_at: string
          currency: string
          id: string
          price_centavos: number
          status: string
          updated_at: string
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "orders"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      create_payment_resubmission: {
        Args: {
          amount_centavos: number
          paid_at: string
          payment_reference: string
          proof_filename: string
          proof_mime: string
          proof_path: string
          proof_sha256: string
          proof_size: number
          submission_user_id: string
          target_method_id: string
          target_order_id: string
        }
        Returns: string
      }
      create_payment_submission: {
        Args: {
          amount_centavos: number
          paid_at: string
          payment_reference: string
          proof_filename: string
          proof_mime: string
          proof_path: string
          proof_sha256: string
          proof_size: number
          submission_user_id: string
          target_method_id: string
          target_order_id: string
        }
        Returns: string
      }
      curriculum_required_drift: {
        Args: { target_course: string }
        Returns: {
          canonical_title: string
          enrollments_counting_required: number
          in_approved_curriculum: boolean
          module_id: string
          module_position: number
          module_required: boolean
          module_status: Database["public"]["Enums"]["module_status"]
        }[]
      }
      enrollment_progress: {
        Args: { target_enrollment: string }
        Returns: {
          checks_outstanding: number
          checks_required: number
          checks_unavailable: number
          final_unlocked: boolean
          percent_complete: number
          percent_studied: number
          required_complete: number
          required_studied: number
          required_total: number
        }[]
      }
      ensure_certificate: {
        Args: { target_enrollment: string }
        Returns: {
          completed_at: string
          course_id: string
          course_title: string
          created_at: string
          enrollment_id: string
          failure_reason: string | null
          final_attempt_id: string
          final_score: number
          generation_lease_until: string | null
          generation_token: string | null
          id: string
          issued_at: string | null
          object_path: string | null
          pdf_sha256: string | null
          required_module_count: number
          revocation_reason: string | null
          revoked_at: string | null
          revoked_by: string | null
          size_bytes: number | null
          status: Database["public"]["Enums"]["certificate_status"]
          student_name: string
          template_sha256: string
          template_version: number
          updated_at: string
          user_id: string
          verification_id: string
        }
        SetofOptions: {
          from: "*"
          to: "certificates"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      fail_certificate_generation: {
        Args: {
          failure: string
          target_certificate: string
          worker_token: string
        }
        Returns: undefined
      }
      grant_manual_enrollment: {
        Args: {
          grant_kind: string
          reason: string
          target_course: string
          target_user: string
        }
        Returns: string
      }
      import_final_quiz_bank: {
        Args: {
          owner_id: string
          source_bank: Json
          source_hash: string
          target_course_slug: string
        }
        Returns: Json
      }
      is_account_active: { Args: { target_user?: string }; Returns: boolean }
      is_admin: { Args: { target_user?: string }; Returns: boolean }
      issue_certificate_access: {
        Args: { caller_user: string; target_certificate: string }
        Returns: Json
      }
      issue_material_access: {
        Args: {
          caller_user: string
          requested_language?: string
          target_module: string
        }
        Returns: Json
      }
      mark_email_failed: {
        Args: {
          failure: string
          retryable: boolean
          target_outbox: string
          worker_token: string
        }
        Returns: undefined
      }
      mark_email_sent: {
        Args: {
          provider_id: string
          target_outbox: string
          worker_token: string
        }
        Returns: undefined
      }
      mark_module_studied: {
        Args: { target_module: string }
        Returns: undefined
      }
      module_knowledge_check_available: {
        Args: { target_module: string }
        Returns: boolean
      }
      module_requirements: {
        Args: { target_enrollment: string }
        Returns: {
          check_available: boolean
          check_completed_at: string
          completed_at: string
          module_id: string
          module_position: number
          outstanding: string
          required: boolean
          requires_check: boolean
          studied_at: string
          title: string
        }[]
      }
      module_requires_knowledge_check: {
        Args: { target_module: string }
        Returns: boolean
      }
      quiz_payload: { Args: { target_attempt: string }; Returns: Json }
      record_completed_refund: {
        Args: {
          actual_amount_centavos: number
          completion_time: string
          external_completion_reference: string
          reason: string
          revoke_access?: boolean
          target_submission: string
        }
        Returns: {
          access_revoked: boolean
          amount_centavos: number
          certificate_decision: string
          created_at: string
          currency: string
          external_reference: string
          id: string
          recorded_by: string
          refunded_at: string
          request_id: string
          submission_id: string
        }
        SetofOptions: {
          from: "*"
          to: "refunds"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      review_payment: {
        Args: { decision: string; reason: string; target_submission: string }
        Returns: string
      }
      set_account_status: {
        Args: { new_status: string; reason: string; target_user: string }
        Returns: undefined
      }
      set_enrollment_access: {
        Args: { new_status: string; reason: string; target_enrollment: string }
        Returns: undefined
      }
      snapshot_curriculum: {
        Args: { target_enrollment: string }
        Returns: undefined
      }
      start_quiz_attempt: {
        Args: { attempt_language: string; target_quiz: string }
        Returns: string
      }
      submit_quiz_attempt: {
        Args: { answers: Json; target_attempt: string }
        Returns: Json
      }
      verify_certificate_record: { Args: { lookup_id: string }; Returns: Json }
    }
    Enums: {
      account_status: "active" | "suspended"
      app_language: "en" | "ceb"
      attempt_state: "in_progress" | "scored"
      certificate_status:
        | "pending"
        | "generating"
        | "active"
        | "failed"
        | "revoked"
      course_status: "draft" | "published" | "archived"
      email_status: "queued" | "sending" | "sent" | "failed"
      enrollment_status: "active" | "suspended" | "revoked"
      module_status: "draft" | "published" | "archived"
      payment_method_type: "gcash" | "maya" | "bank_transfer"
      payment_status:
        | "pending"
        | "approved"
        | "rejected"
        | "resubmission_required"
        | "refunded"
      quiz_kind: "knowledge_check" | "final"
      quiz_version_status: "draft" | "published" | "archived"
      refund_request_status:
        | "submitted"
        | "approved"
        | "denied"
        | "completed"
        | "cancelled"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      account_status: ["active", "suspended"],
      app_language: ["en", "ceb"],
      attempt_state: ["in_progress", "scored"],
      certificate_status: [
        "pending",
        "generating",
        "active",
        "failed",
        "revoked",
      ],
      course_status: ["draft", "published", "archived"],
      email_status: ["queued", "sending", "sent", "failed"],
      enrollment_status: ["active", "suspended", "revoked"],
      module_status: ["draft", "published", "archived"],
      payment_method_type: ["gcash", "maya", "bank_transfer"],
      payment_status: [
        "pending",
        "approved",
        "rejected",
        "resubmission_required",
        "refunded",
      ],
      quiz_kind: ["knowledge_check", "final"],
      quiz_version_status: ["draft", "published", "archived"],
      refund_request_status: [
        "submitted",
        "approved",
        "denied",
        "completed",
        "cancelled",
      ],
    },
  },
} as const
