#!/usr/bin/env bash
# Regenerates src/lib/database.types.ts from the schema the app really runs
# against, not a hand-kept copy.
#
# Modes:
#   --linked   introspect the linked project (read-only introspection, no writes).
#              This is the source of truth for this repository: migration
#              202610050019 reconciles already-seeded curriculum rows and refuses
#              to run against an empty database, so a migrations-only cluster
#              cannot reproduce the deployed schema.
#   default    apply bootstrap + every migration to a throwaway PostgreSQL
#              cluster and introspect that. Useful as a schema/RLL shape check
#              while the migration chain has no data dependencies.
#
# DATABASE_URL=1 is also accepted and introspects that connection instead.
#
# This proves SQL and RLS shape only. It does not validate hosted Auth, Storage,
# signed URLs or Edge Functions.
#
# Usage: ./scripts/generate-db-types.sh --linked
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PG_BIN="${PG_BIN:-/opt/homebrew/bin}"
PGDATA="${PGDATA:-/tmp/academy-types-pgdata}"
PGPORT="${PGPORT:-54329}"
TYPES_DB="academy_types"
OUT="${ROOT}/src/lib/database.types.ts"
SOURCE="throwaway PostgreSQL with all migrations applied"

if [ "${1:-}" = "--linked" ]; then
  SOURCE="linked project schema"
elif [ -n "${1:-}" ]; then
  echo "unknown argument: ${1}" >&2
  echo "usage: ./scripts/generate-db-types.sh [--linked]" >&2
  exit 2
fi

if [ -n "${DATABASE_URL:-}" ]; then
  echo "==> generating types from DATABASE_URL"
  npx supabase gen types typescript --db-url "${DATABASE_URL}" >/tmp/academy-gen-types.raw
elif [ "${SOURCE}" = "linked project schema" ]; then
  echo "==> introspecting the linked project schema"
  npx supabase gen types typescript --linked >/tmp/academy-gen-types.raw
else
  for binary in initdb pg_ctl psql; do
    if [ ! -x "${PG_BIN}/${binary}" ]; then
      echo "missing PostgreSQL binary: ${PG_BIN}/${binary}" >&2
      exit 1
    fi
  done

  cleanup() {
    "${PG_BIN}/pg_ctl" -D "${PGDATA}" -m immediate stop >/dev/null 2>&1 || true
    rm -rf "${PGDATA}"
  }
  trap cleanup EXIT

  echo "==> starting throwaway PostgreSQL on port ${PGPORT}"
  rm -rf "${PGDATA}"
  "${PG_BIN}/initdb" -D "${PGDATA}" -U postgres -A trust >/dev/null
  "${PG_BIN}/pg_ctl" -D "${PGDATA}" -o "-p ${PGPORT} -F" -w start >/dev/null

  export PGHOST=127.0.0.1 PGPORT="${PGPORT}" PGUSER=postgres
  "${PG_BIN}/psql" -X -q -v ON_ERROR_STOP=1 <<'SQL'
create role anon nologin noinherit;
create role authenticated nologin noinherit;
create role service_role nologin noinherit bypassrls;
SQL
  "${PG_BIN}/psql" -X -q -v ON_ERROR_STOP=1 -c "create database ${TYPES_DB}"

  echo "==> applying bootstrap and migrations"
  "${PG_BIN}/psql" -X -q -v ON_ERROR_STOP=1 -d "${TYPES_DB}" -f "${ROOT}/supabase/testharness/bootstrap.sql"
  for migration in "${ROOT}"/supabase/migrations/*.sql; do
    echo "    $(basename "${migration}")"
    "${PG_BIN}/psql" -X -q -v ON_ERROR_STOP=1 -d "${TYPES_DB}" -f "${migration}"
  done

  echo "==> generating types"
  npx supabase gen types typescript \
    --db-url "postgresql://postgres@127.0.0.1:${PGPORT}/${TYPES_DB}?sslmode=disable" \
    >/tmp/academy-gen-types.raw
fi

if [ ! -s /tmp/academy-gen-types.raw ]; then
  echo "type generation produced no output" >&2
  exit 1
fi

# The answer key must never be reachable from the frontend role. If a future
# migration exposes it, this fails loudly instead of shipping a leak.
if grep -q "quiz_answer_keys" /tmp/academy-gen-types.raw; then
  echo "REFUSING: private.quiz_answer_keys appears in generated types" >&2
  exit 1
fi

{
  echo "// GENERATED FILE - do not edit by hand."
  echo "//"
  echo "// Source of truth: supabase/migrations/*.sql, generated by"
  echo "//   npx supabase gen types typescript --linked"
  echo "// (or --db-url <DATABASE_URL>). Regenerate with:"
  echo "//   ./scripts/generate-db-types.sh --linked"
  echo "//"
  echo "// private.quiz_answer_keys is intentionally absent: it lives in a schema the"
  echo "// frontend role cannot read, so correct answers cannot reach the browser."
  echo ""
  cat /tmp/academy-gen-types.raw
} > "${OUT}"

echo
echo "wrote ${OUT} (from ${SOURCE})"
echo "review with: npm run typecheck"